# Override the addresses for the jobs under the diego-api instance group.
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/health_addr?
  value: 0.0.0.0:8890
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=cfdot/properties/bbs?/hostname
  value: 127.0.0.1
- type: replace
  path: /variables/name=diego_bbs_server/options?/alternative_names?/-
  value: '127.0.0.1'

# Disable tuning /proc/sys kernel parameters as locket and bbs are running on containers.
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/set_kernel_parameters?
  value: false

# Add quarks properties for bbs.
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/quarks?
  value:
    ports:
    - name: cell-bbs-api
      protocol: TCP
      internal: 8889 # If you change this values, change the probe below too
    activePassiveProbes:
      bbs-bbs:
        exec:
          command:
          - bash
          - -ce
          - "head -c0 </dev/tcp/${HOSTNAME}/8889"

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=loggr-udp-forwarder/properties?/quarks/envs
  value:
  - name: INDEX
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['statefulset.kubernetes.io/pod-name']
  - name: IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

{{- range $bytes := .Files.Glob "assets/operations/pre_render_scripts/diego-api_*" }}
{{ $bytes | toString }}
{{- end }}
